// Copyright 2012 Google Inc.
// All Rights Reserved.
//
// This file has been auto-generated by GenJsDeps, please do not edit.

goog.addDependency('../../geo/gestalt/client/javascript/apifunction.js', ['ee.ApiFunction'], ['ee.Function', 'ee.Types', 'ee.data', 'goog.object']);
goog.addDependency('../../geo/gestalt/client/javascript/apitestcase.js', ['ee.ApiTestCase'], ['ee', 'ee.data', 'goog.json']);
goog.addDependency('../../geo/gestalt/client/javascript/collection.js', ['ee.Collection'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.CustomFunction', 'ee.Element', 'ee.Filter', 'ee.Types']);
goog.addDependency('../../geo/gestalt/client/javascript/computedobject.js', ['ee.ComputedObject'], ['ee.Encodable', 'ee.Serializer', 'ee.data']);
goog.addDependency('../../geo/gestalt/client/javascript/customfunction.js', ['ee.CustomFunction'], ['ee.Encodable', 'ee.Function', 'ee.Serializer', 'ee.Types', 'goog.array', 'goog.object']);
goog.addDependency('../../geo/gestalt/client/javascript/data.js', ['ee.data', 'ee.data.AlgorithmArgument', 'ee.data.AlgorithmSignature', 'ee.data.AlgorithmsRegistry', 'ee.data.BandDescription', 'ee.data.DownloadId', 'ee.data.FeatureCollectionDescription', 'ee.data.GMEProject', 'ee.data.GeoJSONFeature', 'ee.data.GeoJSONGeometry', 'ee.data.ImageCollectionDescription', 'ee.data.ImageDescription', 'ee.data.ImageList', 'ee.data.MapId', 'ee.data.PixelTypeDescription', 'ee.data.ProcessingResponse', 'ee.data.RawMapId', 'ee.data.TaskStatus', 'ee.data.TaskUpdateActions', 'ee.data.ThumbnailId'], ['goog.Uri', 'goog.json', 'goog.net.XhrIo', 'goog.net.XmlHttp', 'goog.object']);
goog.addDependency('../../geo/gestalt/client/javascript/deserializer.js', ['ee.Deserializer'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.CustomFunction', 'ee.Encodable', 'ee.Function', 'ee.Geometry', 'goog.array', 'goog.json', 'goog.object']);
goog.addDependency('../../geo/gestalt/client/javascript/ee.js', ['ee', 'ee.Algorithms', 'ee.InitState'], ['ee.ApiFunction', 'ee.Collection', 'ee.ComputedObject', 'ee.Element', 'ee.Feature', 'ee.FeatureCollection', 'ee.Filter', 'ee.Function', 'ee.Geometry', 'ee.Image', 'ee.ImageCollection', 'ee.Number', 'ee.String', 'ee.Types', 'ee.data', 'goog.array', 'goog.object']);
goog.addDependency('../../geo/gestalt/client/javascript/element.js', ['ee.Element'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.Types', 'goog.array', 'goog.object']);
goog.addDependency('../../geo/gestalt/client/javascript/encodable.js', ['ee.Encodable'], []);
goog.addDependency('../../geo/gestalt/client/javascript/feature.js', ['ee.Feature'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.Element', 'ee.Geometry']);
goog.addDependency('../../geo/gestalt/client/javascript/featurecollection.js', ['ee.FeatureCollection'], ['ee.ApiFunction', 'ee.Collection', 'ee.ComputedObject', 'ee.Feature', 'ee.Geometry', 'ee.Types', 'goog.array']);
goog.addDependency('../../geo/gestalt/client/javascript/filter.js', ['ee.Filter'], ['ee.ApiFunction', 'ee.ComputedObject', 'goog.array', 'goog.string']);
goog.addDependency('../../geo/gestalt/client/javascript/function.js', ['ee.Function', 'ee.Function.Signature'], ['ee.ComputedObject', 'ee.Encodable', 'ee.Serializer', 'goog.array', 'goog.functions']);
goog.addDependency('../../geo/gestalt/client/javascript/geometry.js', ['ee.Geometry', 'ee.Geometry.LineString', 'ee.Geometry.LinearRing', 'ee.Geometry.MultiLineString', 'ee.Geometry.MultiPoint', 'ee.Geometry.MultiPolygon', 'ee.Geometry.Point', 'ee.Geometry.Polygon', 'ee.Geometry.Rectangle'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.Serializer', 'goog.json.Serializer']);
goog.addDependency('../../geo/gestalt/client/javascript/image.js', ['ee.Image'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.Element', 'ee.Function', 'ee.Geometry', 'ee.Types', 'ee.data', 'goog.array', 'goog.object']);
goog.addDependency('../../geo/gestalt/client/javascript/imagecollection.js', ['ee.ImageCollection'], ['ee.ApiFunction', 'ee.Collection', 'ee.ComputedObject', 'ee.Image', 'ee.Types', 'goog.array']);
goog.addDependency('../../geo/gestalt/client/javascript/number.js', ['ee.Number'], ['ee.ApiFunction', 'ee.ComputedObject']);
goog.addDependency('../../geo/gestalt/client/javascript/serializer.js', ['ee.Serializer'], ['ee.Encodable', 'goog.array', 'goog.crypt.Md5', 'goog.json.Serializer', 'goog.object']);
goog.addDependency('../../geo/gestalt/client/javascript/string.js', ['ee.String'], ['ee.ApiFunction', 'ee.ComputedObject']);
goog.addDependency('../../geo/gestalt/client/javascript/types.js', ['ee.Types'], ['ee.ComputedObject', 'ee.Encodable']);
