// Copyright 2012 Google Inc.
// All Rights Reserved.
//
// This file has been auto-generated by GenJsDeps, please do not edit.

goog.addDependency('../../geo/gestalt/client/javascript/algorithms.js', ['ee.Algorithms'], ['ee.Collection', 'ee.Feature', 'ee.FeatureCollection', 'ee.Image', 'ee.ImageCollection', 'ee.Serializer', 'ee.data', 'goog.object']);
goog.addDependency('../../geo/gestalt/client/javascript/collection.js', ['ee.Collection'], ['ee.Filter', 'ee.Serializer', 'ee.data']);
goog.addDependency('../../geo/gestalt/client/javascript/data.js', ['ee.data'], ['ee', 'goog.Uri', 'goog.json', 'goog.net.XhrIo', 'goog.net.XmlHttp']);
goog.addDependency('../../geo/gestalt/client/javascript/ee.js', ['ee'], []);
goog.addDependency('../../geo/gestalt/client/javascript/feature.js', ['ee.Feature', 'ee.Geometry'], ['ee', 'ee.Image', 'ee.Serializer']);
goog.addDependency('../../geo/gestalt/client/javascript/featurecollection.js', ['ee.FeatureCollection'], ['ee', 'ee.Collection', 'ee.Feature', 'ee.Image', 'ee.Serializer', 'goog.array']);
goog.addDependency('../../geo/gestalt/client/javascript/filter.js', ['ee.Filter'], ['ee', 'ee.Serializer', 'goog.array', 'goog.object']);
goog.addDependency('../../geo/gestalt/client/javascript/image.js', ['ee.Image'], ['ee', 'ee.Collection', 'ee.Serializer', 'ee.data', 'goog.Uri.QueryData']);
goog.addDependency('../../geo/gestalt/client/javascript/imagecollection.js', ['ee.ImageCollection'], ['ee', 'ee.Collection', 'ee.Image', 'ee.Serializer', 'goog.array']);
goog.addDependency('../../geo/gestalt/client/javascript/serializer.js', ['ee.Serializer'], ['goog.json.Serializer']);
