// Copyright 2012 Google Inc.
// All Rights Reserved.
//
// This file has been auto-generated by GenJsDeps, please do not edit.

// Disable Clang formatter for this file.
// See http://goo.gl/SdiwZH
// clang-format off

goog.addDependency('../../geo/gestalt/client/javascript/apifunction.js', ['ee.ApiFunction'], ['ee.ComputedObject', 'ee.Function', 'ee.Types', 'ee.data', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/apitestcase.js', ['ee.ApiTestCase', 'ee.ApiTestCase.BUILTIN_FUNCTIONS'], ['ee', 'ee.data', 'goog.json', 'goog.string', 'goog.testing.TestCase'], false);
goog.addDependency('../../geo/gestalt/client/javascript/arguments.js', ['ee.arguments'], ['ee.ComputedObject', 'goog.array', 'goog.asserts', 'goog.object', 'goog.structs.Set'], false);
goog.addDependency('../../geo/gestalt/client/javascript/collection.js', ['ee.Collection'], ['ee.ApiFunction', 'ee.Element', 'ee.Filter', 'ee.arguments'], false);
goog.addDependency('../../geo/gestalt/client/javascript/computedobject.js', ['ee.ComputedObject'], ['ee.Encodable', 'ee.Serializer', 'ee.data', 'goog.array'], false);
goog.addDependency('../../geo/gestalt/client/javascript/customfunction.js', ['ee.CustomFunction'], ['ee.ComputedObject', 'ee.Function', 'ee.Number', 'ee.Serializer', 'ee.String', 'ee.Types', 'goog.array', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/data.js', ['ee.data', 'ee.data.AbstractTaskConfig', 'ee.data.AlgorithmArgument', 'ee.data.AlgorithmSignature', 'ee.data.AlgorithmsRegistry', 'ee.data.AssetAcl', 'ee.data.AssetAclUpdate', 'ee.data.AssetDescription', 'ee.data.AssetList', 'ee.data.AssetType', 'ee.data.AuthArgs', 'ee.data.AuthResponse', 'ee.data.Band', 'ee.data.BandDescription', 'ee.data.BandMapping', 'ee.data.DownloadId', 'ee.data.FeatureCollectionDescription', 'ee.data.FeatureVisualizationParameters', 'ee.data.FileSource', 'ee.data.FolderDescription', 'ee.data.GeoJSONFeature', 'ee.data.GeoJSONGeometry', 'ee.data.ImageCollectionDescription', 'ee.data.ImageDescription', 'ee.data.ImageTaskConfig', 'ee.data.ImageVisualizationParameters', 'ee.data.IngestionRequest', 'ee.data.MapId', 'ee.data.MapZoomRange', 'ee.data.MissingData', 'ee.data.PixelTypeDescription', 'ee.data.ProcessingResponse', 'ee.data.RawMapId', 'ee.data.ReductionPolicy', 'ee.data.ShortAssetDescription', 'ee.data.SystemTimeProperty', 'ee.data.TableTaskConfig', 'ee.data.TaskListResponse', 'ee.data.TaskStatus', 'ee.data.TaskUpdateActions', 'ee.data.ThumbnailId', 'ee.data.TilesTaskConfig', 'ee.data.Tileset', 'ee.data.VideoTaskConfig'], ['goog.Uri', 'goog.array', 'goog.async.Throttle', 'goog.functions', 'goog.json', 'goog.net.XhrIo', 'goog.net.XmlHttp', 'goog.net.jsloader', 'goog.object', 'goog.string'], false);
goog.addDependency('../../geo/gestalt/client/javascript/date.js', ['ee.Date'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.Types', 'ee.arguments'], false);
goog.addDependency('../../geo/gestalt/client/javascript/deserializer.js', ['ee.Deserializer'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.CustomFunction', 'ee.Date', 'ee.Encodable', 'ee.Function', 'ee.Geometry', 'goog.array', 'goog.json', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/dictionary.js', ['ee.Dictionary'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.Types'], false);
goog.addDependency('../../geo/gestalt/client/javascript/ee.js', ['ee', 'ee.Algorithms', 'ee.InitState'], ['ee.ApiFunction', 'ee.Collection', 'ee.ComputedObject', 'ee.CustomFunction', 'ee.Date', 'ee.Dictionary', 'ee.Element', 'ee.Encodable', 'ee.Feature', 'ee.FeatureCollection', 'ee.Filter', 'ee.Function', 'ee.Geometry', 'ee.Image', 'ee.ImageCollection', 'ee.List', 'ee.Number', 'ee.String', 'ee.Terrain', 'ee.Types', 'ee.data', 'goog.array', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/element.js', ['ee.Element'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.Types', 'goog.array', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/encodable.js', ['ee.Encodable'], [], false);
goog.addDependency('../../geo/gestalt/client/javascript/feature.js', ['ee.Feature'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.Element', 'ee.Geometry', 'ee.arguments', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/featurecollection.js', ['ee.FeatureCollection'], ['ee.ApiFunction', 'ee.Collection', 'ee.ComputedObject', 'ee.Feature', 'ee.Geometry', 'ee.List', 'ee.Types', 'ee.arguments', 'ee.data', 'goog.array'], false);
goog.addDependency('../../geo/gestalt/client/javascript/filter.js', ['ee.Filter'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.arguments', 'goog.array', 'goog.string'], false);
goog.addDependency('../../geo/gestalt/client/javascript/function.js', ['ee.Function', 'ee.Function.Signature'], ['ee.ComputedObject', 'ee.Encodable', 'ee.Serializer', 'ee.Types', 'goog.array', 'goog.functions', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/geometry.js', ['ee.Geometry', 'ee.Geometry.LineString', 'ee.Geometry.LinearRing', 'ee.Geometry.MultiLineString', 'ee.Geometry.MultiPoint', 'ee.Geometry.MultiPolygon', 'ee.Geometry.Point', 'ee.Geometry.Polygon', 'ee.Geometry.Rectangle'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.Serializer', 'ee.Types', 'ee.arguments', 'goog.array', 'goog.json.Serializer', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/image.js', ['ee.Image'], ['ee.ApiFunction', 'ee.ComputedObject', 'ee.Element', 'ee.Function', 'ee.Geometry', 'ee.Types', 'ee.arguments', 'ee.data', 'goog.array', 'goog.json', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/imagecollection.js', ['ee.ImageCollection'], ['ee.ApiFunction', 'ee.Collection', 'ee.ComputedObject', 'ee.Image', 'ee.List', 'ee.Types', 'ee.arguments', 'goog.array'], false);
goog.addDependency('../../geo/gestalt/client/javascript/list.js', ['ee.List'], ['ee.ApiFunction', 'ee.ComputedObject', 'goog.array'], false);
goog.addDependency('../../geo/gestalt/client/javascript/maplayeroverlay.js', ['ee.MapLayerOverlay', 'ee.TileEvent'], ['ee.MapTileManager', 'goog.array', 'goog.dom', 'goog.events', 'goog.events.Event', 'goog.events.EventTarget', 'goog.events.EventType', 'goog.iter', 'goog.net.EventType', 'goog.structs.Set', 'goog.style'], false);
goog.addDependency('../../geo/gestalt/client/javascript/maptilemanager.js', ['ee.MapTileManager'], ['ee.data', 'goog.Disposable', 'goog.Uri', 'goog.array', 'goog.events', 'goog.events.Event', 'goog.events.EventTarget', 'goog.events.EventType', 'goog.net.EventType', 'goog.net.ImageLoader', 'goog.net.XhrIo', 'goog.structs.Map', 'goog.structs.PriorityPool'], false);
goog.addDependency('../../geo/gestalt/client/javascript/number.js', ['ee.Number'], ['ee.ApiFunction', 'ee.ComputedObject'], false);
goog.addDependency('../../geo/gestalt/client/javascript/package.js', ['ee.Package'], ['ee.ApiFunction', 'ee.CustomFunction', 'ee.SavedFunction', 'ee.arguments', 'ee.data'], false);
goog.addDependency('../../geo/gestalt/client/javascript/profiler.js', ['ee.data.Profiler'], ['ee.ApiFunction', 'goog.async.Delay', 'goog.events.Event', 'goog.events.EventTarget', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/savedfunction.js', ['ee.SavedFunction'], ['ee.ApiFunction', 'ee.Function'], false);
goog.addDependency('../../geo/gestalt/client/javascript/serializer.js', ['ee.Serializer'], ['ee.Encodable', 'goog.array', 'goog.crypt.Md5', 'goog.json.Serializer', 'goog.object'], false);
goog.addDependency('../../geo/gestalt/client/javascript/string.js', ['ee.String'], ['ee.ApiFunction', 'ee.ComputedObject'], false);
goog.addDependency('../../geo/gestalt/client/javascript/terrain.js', ['ee.Terrain'], ['ee.ApiFunction'], false);
goog.addDependency('../../geo/gestalt/client/javascript/types.js', ['ee.Types'], ['ee.ComputedObject'], false);
